# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20170724_1945'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='incident',
            managers=[
            ],
        ),
    ]
