# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20170725_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='picture',
            field=models.CharField(default='This is picture', max_length=100),
        ),
    ]
